### ISSUE TITLE
The RAM used by Revery is over 900MB. Why?

### ISSUE THREAD

**Issue by hexiangdong2017** [revery-ui/revery#453]

**Comment by Et7f3** [comment]
What have you done in your app. Are you loading lot of photos and ressources. are you sure it's revery and not you other part of you project.

**Comment by bryphe** [comment]
Hmm, there's no information to go on here - without more information, this isn't actionable.

Some information that would be helpful in diagnosing this, @hexiangdong2017 :
- What operating system are you using?
- What revery version are you using?
- What kind of application are you running? Is it the example app in this repo, the `revery-quick-start` app, or another?
- Is there a minimal repro available?
- Does the app immediately use the 900MB, or is it a gradual climb?

**Comment by hexiangdong2017** [comment]
1.Windows 10 Professional
2.the latest version I clone from the revery-quick-start, but I write my own App.
3.I have ziped the project and uploaded to Google Driver:  https://drive.google.com/open?id=1B3y6BR3cIETAqlO-awMs22l3BhQXOAhP
4.and the App I build:  https://drive.google.com/open?id=1gJmNTBP0thyqcuxzG1PL95CXI2VA-gts
4.It is gradual climb from 68M to 900M.

**Comment by hexiangdong2017** [comment]
I'm new to Revery and I know little about it

**Comment by lessp** [comment]
Hey @hexiangdong2017, could you perhaps share a link to a github-repo? That would make it easier for people to have a look! 🙂

**Comment by hexiangdong2017** [comment]
@lessp  https://github.com/hexiangdong2017/MixSerial

**Comment by bryphe** [comment]
Thanks for the github repo, @hexiangdong2017 !

Tried building on both Mac & Windows, and hit this error:
```
info @serialport/bindings@2.0.7: running install lifecycle                                                      
error command failed: cd  '/Users/bryphe/.esy/source/s/serialport__s__bindings__2.0.7__92893246' && prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild
      output:
               /Users/bryphe/.esy/source/s/serialport__s__bindings__2.0.7__92893246/_esy/pnp.js:3541
    throw resolutionError;
    ^

Error: Couldn't find a suitable Node resolution for unqualified path "/Users/bryphe/.config/yarn/global/node_modules"
    at makeError (/Users/bryphe/.esy/source/s/serialport__s__bindings__2.0.7__92893246/_esy/pnp.js:54:17)
    at Object.resolveUnqualified (/Users/bryphe/.esy/source/s/serialport__s__bindings__2.0.7__92893246/_esy/pnp.js:3467:11)
    at Object.resolveRequest (/Users/bryphe/.esy/source/s/serialport__s__bindings__2.0.7__92893246/_esy/pnp.js:3536:20)
    at Function.Module._resolveFilename (/Users/bryphe/.esy/source/s/serialport__s__bindings__2.0.7__92893246/_esy/pnp.js:3639:32)
    at Function.Module._load (/Users/bryphe/.esy/source/s/serialport__s__bindings__2.0.7__92893246/_esy/pnp.js:3585:31)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/bryphe/.config/yarn/global/node_modules/.bin/node-gyp:13:11)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)

error: error running command          
```

Is there a chance to get a repro that doesn't require the `serialports` package? 🤔

**Comment by bryphe** [comment]
I suspect it is related to this issue: https://github.com/revery-ui/revery/issues/430 - there is a memory leak for certain types of geometry (specifically - borders). I wanted to try and remove border rendering as a first pass attempt.

**Comment by bryphe** [comment]
We just discovered a memory leak that impacted `Hooks.reducer` and `Hooks.state` - fixed here: https://github.com/revery-ui/revery/pull/480

@hexiangdong2017 - do you still see the leak on latest `master` Revery?

**Comment by lessp** [comment]
Closing due to inactivity. Happy to re-open if the issue remains!
